services:

  postgres:
    image: postgres:13-alpine
    ports:
      - '5432:5432'
    volumes:
      -  ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=login12345
      - POSTGRES_PASSWORD=9mREsvXDs9Gk89Ef


  mysql:
    image: mysql:8.0.34
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass

  node_app:
    build: ./gate-simulator
    image: node-app:1.0
    ports:
      - '9999:9999'