services:
  node_app:
    build: ./gate-simulator
    image: node-app:1.0
    ports:
      - '9999:9999'

  postgres:
    image: postgres:13-alpine
    restart: always
    ports:
      - '5432:5432'

    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass

  mysql:
    image: mysql:8.0.34
    restart: always
    ports:
      - '3306:3306'

    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass